import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { RoomPage } from './vewersh'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>M4XLR.TV</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          M4xlr-TV
        </h1>

        <p className={styles.description}>
          A continuos livestream experiment
        </p>
        <RoomPage/>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
